### ISSUE TITLE
Video Trim Issue: Plays Beyond Trimmed Section on [Android]

### ISSUE THREAD

**Issue by Vignesh1318** [maitrungduc1410/react-native-video-trim#76]
Check the below link @maitrungduc1410 

https://github.com/maitrungduc1410/react-native-video-trim/issues/65#issuecomment-2404699419

**Comment by maitrungduc1410** [comment]
@Vignesh1318 thanks for reporting, I'll check it and reply you soon

**Comment by Vignesh1318** [comment]
> @Vignesh1318 thanks for reporting, I'll check it and reply to you soon

Is this any update @maitrungduc1410 ??

**Comment by maitrungduc1410** [comment]
This week I'm on holiday, will check by the of this week when I'm back

**Comment by maitrungduc1410** [comment]
hi @Vignesh1318 I fixed the issue, please upgrade to 2.2.8

**Comment by Vignesh1318** [comment]
> hi @Vignesh1318 I fixed the issue, please upgrade to 2.2.8

Hi @maitrungduc1410 

This issue working fine but I have another issue. When the user trims the video and clicks to play the trimmed section, the video starts playing at the trimmed position, but the cursor automatically adjusts back to the start. I've attached the video for reference. Can you please check?

[New Tab.webm](https://github.com/user-attachments/assets/394fbfdd-e592-402f-9980-970fecd317e9)

**Comment by maitrungduc1410** [comment]
I'll check it, thanks for reporting

**Comment by maitrungduc1410** [comment]
hey @Vignesh1318 are you able to reproduce consistently, on different videos? I'm trying and can't reproduce it

**Comment by Vignesh1318** [comment]
> hey @Vignesh1318 are you able to reproduce consistently, on different videos? I'm trying and can't reproduce it

Yes @maitrungduc1410 consistently I'm able to reproduce this.

**Comment by Vignesh1318** [comment]
> > hey @Vignesh1318 are you able to reproduce consistently, on different videos? I'm trying and can't reproduce it
> 
> Yes @maitrungduc1410 consistently I'm able to reproduce this.

It's playing differently Please check the attachment below 

https://github.com/user-attachments/assets/1c4af384-ed1a-4c0e-b959-87bf3a59e06f

**Comment by maitrungduc1410** [comment]
hi @Vignesh1318 I don't get it, also not able to reproduce, can you help me find a case that you can reproduce it consistently?

**Comment by Vignesh1318** [comment]
> hi @Vignesh1318 I don't get it, also not able to reproduce, can you help me find a case that you can reproduce it consistently?

Hi @maitrungduc1410 I'll attach the cases tomorrow. I'm on holiday and will upload when I'm back.

**Comment by Lakston** [comment]
I have something similar but not sure if it is linked, I will open an issue if it is not, but for me, if I select a video with a 2 seconds length with a minDuration of 5 seconds, if you click on the left or right handle the selection will expand to 5 seconds

**Comment by maitrungduc1410** [comment]
> I have something similar but not sure if it is linked, I will open an issue if it is not, but for me, if I select a video with a 2 seconds length with a minDuration of 5 seconds, if you click on the left or right handle the selection will expand to 5 seconds

can I have your code?

**Comment by Lakston** [comment]
There is really nothing special in the code, it's simply

```
  showEditor(payload.content.uri || "", {
    minDuration: 5,
    maxDuration: 15,
  });
```

And I pick a video that has a duration of less than 5 seconds and touch the left or right handle, the bloc will expand out of the screen to match the 5 seconds duration

https://github.com/user-attachments/assets/74559a4a-14ee-43f9-8112-f72201940b20

**Comment by Vignesh1318** [comment]
> hi @Vignesh1318 I don't get it, also not able to reproduce, can you help me find a case that you can reproduce it consistently?

Hi @maitrungduc1410 

I mentioned that the issue is working fine on a real device.

Sorry for the delayed response.

**Comment by maitrungduc1410** [comment]
@Lakston pls upgrade to 2.2.10, I fixed that issue

**Comment by Lakston** [comment]
The issue is not fixed, the handle will still extend out of the screen as seen in the video, I had to prevent users from being able to import a video with a duration < minDuration

**Comment by maitrungduc1410** [comment]
@Lakston hmm, weird, I handled this case,

are you using latest version? Can dhow your screen recording again? With your code and your test file also.
