### ISSUE TITLE
Black Screen on First Frame When Playing Trimmed Video in React Native Video

### ISSUE THREAD

**Issue by Vignesh1318** [maitrungduc1410/react-native-video-trim#89]
When I trim a video, I drag the slider to a starting point, and I also drag the slider to the last point and trim it. After trimming, I get the URL from the onFinishing event and pass that URL to play in the React Native video player. When I preview it, the first frame appears as a black screen. I checked the React Native Video issue, but it doesn't seem to be a React Native Video issue. I'll attach the original and trimmed recorder videos—can you please check and confirm?

original video 

https://github.com/user-attachments/assets/85959630-e219-4cc9-aeee-fe511b2d7f17

Recorder video

https://github.com/user-attachments/assets/2d17d619-6044-48ca-9c16-2a0ae9b23cf9

**Comment by Vignesh1318** [comment]
> On which platform do you face the issue?

@maitrungduc1410 Its happen in android only

**Comment by maitrungduc1410** [comment]
@Vignesh1318 what are options you passed to showEditor?

**Comment by Vignesh1318** [comment]
> [@Vignesh1318](https://github.com/Vignesh1318) what are options you passed to showEditor?

I only pass autoplay: true. @maitrungduc1410

**Comment by maitrungduc1410** [comment]
I tried, it works just fine, I'm using react-native-video-player to preview the output, no black frame

https://github.com/user-attachments/assets/08a39df4-2f17-4af1-be6c-b501b11b7a8b

**Comment by Vignesh1318** [comment]
> I tried, it works just fine, I'm using react-native-video-player to preview the output, no black frame
> 
>  a929afd2-93f9-4ec4-9832-38cadb3004fe.mp4

I tried, but I am able to reproduce the issue.

Can you please check the attachment below?


https://github.com/user-attachments/assets/7efd8e57-4ebe-4f47-b282-6bd197e4df70

**Comment by Vignesh1318** [comment]
> > I tried, it works just fine, I'm using react-native-video-player to preview the output, no black frame
> > a929afd2-93f9-4ec4-9832-38cadb3004fe.mp4
> 
> I tried, but I am able to reproduce the issue.
> 
> Can you please check the attachment below? @maitrungduc1410 
> 
>  WhatsApp.Video.2025-03-18.at.11.47.04.mp4

**Comment by maitrungduc1410** [comment]
@Vignesh1318 please upgrade to 3.0.3, I fixed the issue.

**Comment by Vignesh1318** [comment]
> [@Vignesh1318](https://github.com/Vignesh1318) please upgrade to 3.0.3, I fixed the issue.

I tried in this release (3.0.3), but the issue is not fixed. I have attached the details below. Can you please check? @maitrungduc1410 


https://github.com/user-attachments/assets/4ed6b29c-0043-4d54-8876-96af7f164ef1


Original attachment : https://github.com/user-attachments/assets/7efd8e57-4ebe-4f47-b282-6bd197e4df70

**Comment by maitrungduc1410** [comment]
@Vignesh1318 I tried again with your original attachment, no issue, it works just fine, can you try upgrade to 3.0.5 and try again?

https://github.com/user-attachments/assets/d75f3ddd-883a-4951-a60f-bac17d1c5787

**Comment by Vignesh1318** [comment]
@maitrungduc1410 It's working fine in version 3.0.5. Thanks for the support!
